name: JMeter API Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      spec_path:
        description: 'Test Suite File'
        required: true
        default: 'my-practices/api_request_own_server.jmx'
        type: choice
        options:
          - 'my-practices/api_request_own_server.jmx'
          - 'my-practices/Assertion.jmx'

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: ${{ github.event.inputs.spec_path || 'my-practices/api_request_own_server.jmx' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: npm install -g json-server

    - name: Install JMeter
      run: |
        wget https://apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        echo "$(pwd)/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    - name: Create Results Directory
      run: mkdir -p jmeter-results

    - name: Run JSON Server
      run: |
        json-server --watch api_own_server/db.json --port 3000 &
        sleep 5

    - name: Run JMeter Test
      run: |
        jmeter -n -t $SPEC_PATH -l jmeter-results/results.jtl -e -o jmeter-results/

    - name: Upload JMeter Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: jmeter-results/
        retention-days: 5

    - name: Telegram Notification
      if: always()
      shell: bash
      env:
        TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        STATUS="${{ job.status }}"
        PROJECT=$(basename "$GITHUB_REPOSITORY")
        BRANCH="${GITHUB_REF#refs/heads/}"
        COMMIT="${GITHUB_SHA}"
        MESSAGE="GitHub Actions Pipeline Completed\n\nProject: $PROJECT\nBranch: $BRANCH\nCommit: $COMMIT\nWorkflow: ${{ github.workflow }}\nStatus: $STATUS\nPath: $SPEC_PATH"
        RESPONSE=$(curl -sS -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TG_CHAT_ID}" \
          -d text="$(printf '%b' "$MESSAGE")")
