name: E2E JMeter API Testing

# permissions:
#   contents: read
#   actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      spec_path:
        description: 'Test Suite File'
        required: true
        default: 'my-practices/api_request_own_server.jmx'
        type: choice
        options:
          - 'my-practices/api_request_own_server.jmx'
          - 'my-practices/Assertion.jmx'
      csv_path:
        description: 'CSV File Path'
        required: true
        default: 'csv/test_data.csv'
        type: choice
        options:
          - 'csv/test_data.csv'
          - 'csv/another_test_data.csv'

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: ${{ github.event.inputs.spec_path || 'my-practices/api_request_own_server.jmx' }}
      CSV_FILE_PATH: ${{ github.event.inputs.csv_path || 'csv/test_data.csv' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: |
        npm install -g json-server
        wget https://apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        echo "$(pwd)/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    # - name: Install JMeter
    #   run: |
    #     wget https://apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
    #     tar -xzf apache-jmeter-5.6.3.tgz
    #     echo "$(pwd)/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    # - name: Create Results Directory
    #   run: mkdir -p jmeter-results

    - name: Run JSON Server
      run: |
        json-server --watch api_own_server/db.json --port 3000 &
        sleep 5

    - name: Run JMeter Test
      run: |
        mkdir -p jmeter-results
        jmeter -n -t $SPEC_PATH -l jmeter-results/results.jtl -e -o jmeter-results/ -Jcsv_path=${CSV_FILE_PATH}

    - name: Upload JMeter Artifacts
      if: always()
      id: artifact_upload
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: jmeter-results/
        retention-days: 5

    - name: Zip the HTML Report
      if: always()
      run: |
        zip -r jmeter-reports.zip jmeter-results

    - name: Telegram Notification
      if: always()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        REPO_PATH="${{ github.repository }}"
        BRANCH="${GITHUB_REF#refs/heads/}"
        STATUS="${{ job.status }}"
        PROJECT=$(basename "$GITHUB_REPOSITORY")
        COMMIT="${GITHUB_SHA}"
        MESSAGE="GitHub Actions Pipeline Completed\n\nProject: $PROJECT\nBranch: $BRANCH\nCommit: $COMMIT\nWorkflow: ${{ github.workflow }}\nStatus: $STATUS\nPath: $SPEC_PATH\nReport: $DOWNLOAD_REPORT"
        RESPONSE=$(curl -sS -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendDocument" \
          -d chat_id="${TG_CHAT_ID}" \
          -d document=@"jmeter-reports.zip" \
          -d caption="$MESSAGE"
  # -d text="$(printf '%b' "$MESSAGE")")
  # Link to specific workflow
  # curl -sS -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage"
  # REPORT_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  # ARTIFACT_ID="${{ steps.artifact_upload.outputs.artifact-id }}"
  # "https://nightly.link/${{ github.repository }}/actions/artifacts/jmeter-reports.zip"
  # ARTIFACT_ID="${{ steps.artifact_upload.outputs.artifact-id }}"
  # DOWNLOAD_REPORT="https://github.com/$REPO_PATH/actions/runs/${{ github.run_id }}/artifacts/$ARTIFACT_ID"
